/** Constants */
export const PYFLYBY_CELL_TAG = 'pyflyby-cell';
export const PYFLYBY_START_MSG = '# THIS CELL WAS AUTO-GENERATED BY PYFLYBY\n';
export const PYFLYBY_END_MSG = '# END AUTO-GENERATED BLOCK\n';
export const PYFLYBY_COMMS = {
  MISSING_IMPORTS: 'pyflyby.missing_imports',
  FORMAT_IMPORTS: 'pyflyby.format_imports',
  INIT: 'pyflyby.init_comms',
  TIDY_IMPORTS: 'pyflyby.tidy_imports'
};
